name: modbus
version: 0.2.0
homepage: https://github.com/Hacker-CB/modbus-dart
description: Simple Modbus client library for dart. Currently only the TCP connection is supported.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.1

dev_dependencies:
  test: ^1.17.10
